baseURL = "https://paulonajourney.com/"
theme = "hugo-apero"
languageCode = "de"
title = "Paul on a Journey"
author = "Paul Hoffmann"
copyright = ""
googleAnalytics = ""
metaDataFormat = "yaml"
footnoteReturnLinkContents = "&#8617;"
[pagination]
  pagerSize = 5
preserveTaxonomyNames = true
enableEmoji = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true
    hardwraps = false 
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2
    ordered = false
  [markup.highlight]
    style = "github"
    
[params]
  orgName = "Paul Hoffmann"
  orgLocal = "Fredericton, Canada"
  description = "Reisen, Bastelprojekte und Abenteuer mit der Familie."
  favicon = "img/favicon.ico"
  logo = "img/blogophonic-mark-dark.png"
  mainSections = ["blog"]
  navallcaps = true
  socialInHeader = false
  socialInFooter = true
  sharing_image = "img/papillons.jpg"
  theme = "sky"
  custom_theme = "" 
  customtextFontFamily = "Commissioner"
  customheadingFontFamily = "Fraunces"
  textFontFamily = "sans-serif"
  headingFontFamily = "sans-serif"
  comments = ""

  [[params.social]]
      icon      = "github"
      icon_pack = "fab"
      url       = "https://github.com/nestamarl"
  [[params.social]]
      icon      = "rss"
      icon_pack = "fas"
      url       = "/blog/index.xml"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[menu]
  [[menu.header]]
    name = "About"
    title = "About"
    url = "/about/"
    weight = 1
  [[menu.header]]
    name = "Blog"
    title = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.footer]]
    name = "Contact"
    title = "Contact"
    url = "/contact/"
    weight = 1

[privacy]
  [privacy.googleAnalytics]
    disable = false
    anonymizeIP = true
    respectDoNotTrack = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM)$']
  [security.funcs]
    getenv = ['^HUGO_', 'HUGO_BLOGDOWN_POST_RELREF']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']